CONST S=20;CONST M=40;CONST LL=60;

A:=CLOSE>OPEN;
B:=A&&CLOSE>MA(CLOSE,S)&&CLOSE>MA(CLOSE,M)&&CLOSE>MA(CLOSE,LL);
CC:=B&&OPEN<MA(CLOSE,M)&&OPEN<MA(CLOSE,LL);
CSFRO:CC&&(CLOSE-OPEN)>0.0618*CLOSE;