AA:=VOL>REF(VOL,1)||VOL>CAPITAL;
BB:=OPEN>=(REF(HIGH,1))&&REF(HIGH,1)>(REF(HIGH,2)*1.06);
CC:=CLOSE>(REF(CLOSE,1))-(REF(CLOSE,1)*0.01);
DD:=CLOSE<(HIGH*0.965) && HIGH>(OPEN*1.05);
EE:=LOW<OPEN && LOW<CLOSE &&  HIGH>(REF(CLOSE,1)*1.06);
FF:=(HIGH-(MAX(OPEN,CLOSE)))/2>(MIN(OPEN,CLOSE))-LOW;
GG:=(ABS(OPEN-CLOSE))/2<(MIN(OPEN,CLOSE)-LOW);
STAR:AA&&BB&&CC&&DD&&EE&&FF&&GG;